/**
 * Mock data used when the Flask backend is unavailable.
 * Shared between /api/document and /api/analyze routes.
 */
export const MOCK_DATA = {
  process: `1. Purpose and Scope

This standard operating procedure (SOP) defines the process for handling customer personal data within the organization. It applies to all departments that collect, store, process, or transmit personally identifiable information (PII) from customers, including but not limited to: names, email addresses, phone numbers, payment information, and browsing history.

All employees and contractors must adhere to this procedure to ensure compliance with the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), and internal data governance policies.

2. Data Collection

2.1 Customer data shall only be collected for specified, explicit, and legitimate purposes. Data collection forms must include a clear privacy notice explaining how the data will be used.

2.2 Consent must be obtained before collecting any personal data. Consent mechanisms must be opt-in (not pre-checked boxes) and must be freely given, specific, informed, and unambiguous.

2.3 The minimum amount of data necessary for the stated purpose shall be collected. No additional fields may be added to forms without approval from the Data Protection Officer (DPO).

3. Data Storage and Security

3.1 All personal data must be stored in encrypted form using AES-256 encryption at rest. Data in transit must be protected using TLS 1.2 or higher.

3.2 Access to personal data is restricted to authorized personnel only. Role-based access control (RBAC) must be implemented and reviewed quarterly.

3.3 Backups of personal data must be performed daily and stored in a geographically separate location. Backup media must also be encrypted.

3.4 Data retention periods must be defined for each category of personal data. Data must be securely deleted when the retention period expires using approved sanitization methods.

4. Data Processing

4.1 Personal data shall only be processed in accordance with the purpose for which it was collected. Any new processing activity requires a Data Protection Impact Assessment (DPIA).

4.2 Third-party processors must sign a Data Processing Agreement (DPA) before receiving access to any personal data. The DPA must include clauses on data security, breach notification, and sub-processor restrictions.

4.3 Automated decision-making and profiling activities must provide individuals with the right to opt out and to request human review of decisions that significantly affect them.

5. Data Subject Rights

5.1 The organization must respond to data subject access requests (DSARs) within 30 calendar days.

5.2 Individuals have the right to request rectification of inaccurate data, and the organization must action such requests within 15 business days.

5.3 The right to erasure ("right to be forgotten") must be honored unless the data is required for legal compliance or legitimate business purposes.

6. Incident Response

6.1 Any suspected data breach must be reported to the DPO within 24 hours of discovery. The DPO will assess the severity and determine whether notification to supervisory authorities and affected individuals is required.

6.2 A breach notification to the supervisory authority must be made within 72 hours of becoming aware of the breach, as required by GDPR Article 33.

6.3 All data breaches must be documented in the breach register, including the nature of the breach, data subjects affected, and remedial actions taken.`,

  chunks: [
    { chunk_id: "GDPR-5.1b", chunk_text: "Personal data shall be collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes. Further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall not be considered to be incompatible with the initial purposes." },
    { chunk_id: "GDPR-5.1c", chunk_text: "Personal data shall be adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed." },
    { chunk_id: "GDPR-5.1d", chunk_text: "Personal data shall be accurate and, where necessary, kept up to date; every reasonable step must be taken to ensure that personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay." },
    { chunk_id: "GDPR-5.1e", chunk_text: "Personal data shall be kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed. Personal data may be stored for longer periods insofar as the data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes." },
    { chunk_id: "GDPR-5.1f", chunk_text: "Personal data shall be processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures." },
    { chunk_id: "GDPR-7", chunk_text: "Where processing is based on consent, the controller shall be able to demonstrate that the data subject has consented to processing of his or her personal data. The request for consent shall be presented in a manner which is clearly distinguishable from the other matters, in an intelligible and easily accessible form, using clear and plain language." },
    { chunk_id: "GDPR-12.3", chunk_text: "The controller shall provide information on action taken on a request to the data subject without undue delay and in any event within one month of receipt of the request. That period may be extended by two further months where necessary, taking into account the complexity and number of the requests." },
    { chunk_id: "GDPR-17", chunk_text: "The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay and the controller shall have the obligation to erase personal data without undue delay where the personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed." },
    { chunk_id: "GDPR-20", chunk_text: "The data subject shall have the right to receive the personal data concerning him or her, which he or she has provided to a controller, in a structured, commonly used and machine-readable format and have the right to transmit those data to another controller without hindrance." },
    { chunk_id: "GDPR-25", chunk_text: "Taking into account the state of the art, the cost of implementation and the nature, scope, context and purposes of processing as well as the risks of varying likelihood and severity for rights and freedoms of natural persons, the controller shall implement appropriate technical and organisational measures for ensuring that, by default, only personal data which are necessary for each specific purpose of the processing are processed." },
    { chunk_id: "GDPR-28", chunk_text: "Processing by a processor shall be governed by a contract or other legal act that is binding on the processor with regard to the controller and that sets out the subject-matter and duration of the processing, the nature and purpose of the processing, the type of personal data and categories of data subjects." },
    { chunk_id: "GDPR-32", chunk_text: "The controller and the processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including the pseudonymisation and encryption of personal data." },
    { chunk_id: "GDPR-33", chunk_text: "In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority." },
    { chunk_id: "GDPR-35", chunk_text: "Where a type of processing in particular using new technologies, and taking into account the nature, scope, context and purposes of the processing, is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall, prior to the processing, carry out an assessment of the impact of the envisaged processing operations on the protection of personal data." },
    { chunk_id: "ISO-A.7.2.2", chunk_text: "All employees of the organization and, where relevant, contractors shall receive appropriate awareness education and training and regular updates in organizational policies and procedures, as relevant for their job function." },
    { chunk_id: "ISO-A.9.2.5", chunk_text: "Asset owners shall review users' access rights at regular intervals. For high-risk or sensitive data processing, access reviews should be conducted at least monthly to ensure timely detection of unauthorized access changes." },
    { chunk_id: "ISO-A.12.3", chunk_text: "Backup copies of information, software and system images shall be taken and tested regularly in accordance with an agreed backup policy. Backup media shall be stored securely, preferably at a geographically remote site." },
    { chunk_id: "ISO-A.16.1.2", chunk_text: "Information security events shall be reported through appropriate management channels as quickly as possible. The organization shall define a clear escalation path and severity classification matrix to ensure incidents are handled proportionally to their impact." },
    { chunk_id: "ISO-A.18.1.4", chunk_text: "Privacy and protection of personally identifiable information shall be ensured as required in relevant legislation and regulation where applicable. The organization shall establish a data privacy policy and communicate it to all persons involved in the processing of personally identifiable information." },
  ],

  segments: [
    { id: "seg-001", process_id: 1, category: "COMPLIANT", short_evidence: "Data collection is limited to specified, explicit, and legitimate purposes with clear privacy notices.", easy_rule: "Purpose limitation principle (GDPR Art. 5(1)(b))", chunk_id: "GDPR-5.1b", chunk_text: "Personal data shall be collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes. Further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall not be considered to be incompatible with the initial purposes.", extracted_process_segment: "Customer data shall only be collected for specified, explicit, and legitimate purposes. Data collection forms must include a clear privacy notice explaining how the data will be used." },
    { id: "seg-002", process_id: 2, category: "COMPLIANT", short_evidence: "Consent is required before data collection with opt-in mechanisms that are freely given and unambiguous.", easy_rule: "Conditions for consent (GDPR Art. 7)", chunk_id: "GDPR-7", chunk_text: "Where processing is based on consent, the controller shall be able to demonstrate that the data subject has consented to processing of his or her personal data. The request for consent shall be presented in a manner which is clearly distinguishable from the other matters, in an intelligible and easily accessible form, using clear and plain language.", extracted_process_segment: "Consent must be obtained before collecting any personal data. Consent mechanisms must be opt-in (not pre-checked boxes) and must be freely given, specific, informed, and unambiguous." },
    { id: "seg-003", process_id: 3, category: "COMPLIANT", short_evidence: "Data minimization is enforced by collecting only the minimum necessary data with DPO approval for changes.", easy_rule: "Data minimization (GDPR Art. 5(1)(c))", chunk_id: "GDPR-5.1c", chunk_text: "Personal data shall be adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed.", extracted_process_segment: "The minimum amount of data necessary for the stated purpose shall be collected. No additional fields may be added to forms without approval from the Data Protection Officer (DPO)." },
    { id: "seg-004", process_id: 4, category: "COMPLIANT", short_evidence: "AES-256 encryption at rest and TLS 1.2+ in transit meet security requirements.", easy_rule: "Security of processing (GDPR Art. 32)", chunk_id: "GDPR-32", chunk_text: "The controller and the processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including the pseudonymisation and encryption of personal data.", extracted_process_segment: "All personal data must be stored in encrypted form using AES-256 encryption at rest. Data in transit must be protected using TLS 1.2 or higher." },
    { id: "seg-005", process_id: 5, category: "NON-COMPLIANT", short_evidence: "RBAC is reviewed quarterly, but GDPR best practices recommend at least monthly reviews for high-risk data.", easy_rule: "Access control review frequency (ISO 27001 A.9.2.5)", chunk_id: "ISO-A.9.2.5", chunk_text: "Asset owners shall review users' access rights at regular intervals. For high-risk or sensitive data processing, access reviews should be conducted at least monthly to ensure timely detection of unauthorized access changes.", extracted_process_segment: "Access to personal data is restricted to authorized personnel only. Role-based access control (RBAC) must be implemented and reviewed quarterly." },
    { id: "seg-006", process_id: 6, category: "COMPLIANT", short_evidence: "Daily encrypted backups stored in a geographically separate location meet business continuity requirements.", easy_rule: "Backup and recovery (ISO 27001 A.12.3)", chunk_id: "ISO-A.12.3", chunk_text: "Backup copies of information, software and system images shall be taken and tested regularly in accordance with an agreed backup policy. Backup media shall be stored securely, preferably at a geographically remote site.", extracted_process_segment: "Backups of personal data must be performed daily and stored in a geographically separate location. Backup media must also be encrypted." },
    { id: "seg-007", process_id: 7, category: "NO EVIDENCE", short_evidence: "No mention of data portability or providing data in a machine-readable format upon request.", easy_rule: "Right to data portability (GDPR Art. 20)", chunk_id: "GDPR-20", chunk_text: "The data subject shall have the right to receive the personal data concerning him or her, which he or she has provided to a controller, in a structured, commonly used and machine-readable format and have the right to transmit those data to another controller without hindrance.", extracted_process_segment: "" },
    { id: "seg-008", process_id: 8, category: "NON-COMPLIANT", short_evidence: "DSARs have a 30-day response window, but GDPR requires response without undue delay and within one month (which can be shorter).", easy_rule: "Response timeline for DSARs (GDPR Art. 12(3))", chunk_id: "GDPR-12.3", chunk_text: "The controller shall provide information on action taken on a request to the data subject without undue delay and in any event within one month of receipt of the request. That period may be extended by two further months where necessary, taking into account the complexity and number of the requests.", extracted_process_segment: "The organization must respond to data subject access requests (DSARs) within 30 calendar days." },
    { id: "seg-009", process_id: 9, category: "NON-COMPLIANT", short_evidence: "Breach must be reported to DPO within 24 hours, but there is no defined escalation path or severity classification matrix.", easy_rule: "Incident escalation procedures (ISO 27001 A.16.1.2)", chunk_id: "ISO-A.16.1.2", chunk_text: "Information security events shall be reported through appropriate management channels as quickly as possible. The organization shall define a clear escalation path and severity classification matrix to ensure incidents are handled proportionally to their impact.", extracted_process_segment: "Any suspected data breach must be reported to the DPO within 24 hours of discovery. The DPO will assess the severity and determine whether notification to supervisory authorities and affected individuals is required." },
    { id: "seg-010", process_id: 10, category: "COMPLIANT", short_evidence: "72-hour breach notification to supervisory authority aligns with GDPR Article 33 requirements.", easy_rule: "Breach notification timing (GDPR Art. 33)", chunk_id: "GDPR-33", chunk_text: "In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority.", extracted_process_segment: "A breach notification to the supervisory authority must be made within 72 hours of becoming aware of the breach, as required by GDPR Article 33." },
    { id: "seg-011", process_id: 11, category: "NO EVIDENCE", short_evidence: "No mention of regular staff training on data protection procedures and awareness programs.", easy_rule: "Security awareness training (ISO 27001 A.7.2.2)", chunk_id: "ISO-A.7.2.2", chunk_text: "All employees of the organization and, where relevant, contractors shall receive appropriate awareness education and training and regular updates in organizational policies and procedures, as relevant for their job function.", extracted_process_segment: "" },
    { id: "seg-012", process_id: 12, category: "COMPLIANT", short_evidence: "Third-party processors must sign DPAs covering security, breach notification, and sub-processor restrictions.", easy_rule: "Processor agreements (GDPR Art. 28)", chunk_id: "GDPR-28", chunk_text: "Processing by a processor shall be governed by a contract or other legal act that is binding on the processor with regard to the controller and that sets out the subject-matter and duration of the processing, the nature and purpose of the processing, the type of personal data and categories of data subjects.", extracted_process_segment: "Third-party processors must sign a Data Processing Agreement (DPA) before receiving access to any personal data. The DPA must include clauses on data security, breach notification, and sub-processor restrictions." },
  ],
}
